apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapi-demo
  labels:
    app: fastapi-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: fastapi-demo
  template:
    metadata:
      labels:
        app: fastapi-demo
    spec:
      containers:
      - name: fastapi-demo
        image: fastapi-demo:latest  # uses image built inside Minikube Docker
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: ENV
          value: "production"

---
apiVersion: v1
kind: Service
metadata:
  name: fastapi-demo-service
spec:
  type: NodePort
  selector:
    app: fastapi-demo
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30080  # access via minikube IP:30080
